###############################################################################
# WeeWX wFrog Skin                                                            #
# Copyright (C) 2026 Marcin Kowalik <mkowalik@agh.edu.pl>                    #
# SPDX-License-Identifier: GPL-3.0-or-later                                   #
###############################################################################

SKIN_NAME = Wfrog
SKIN_VERSION = 0.1.0

[CheetahGenerator]
    encoding = utf8

    [[ToDate]]
        [[[index]]]
            template = index.html.tmpl

[CopyGenerator]
    copy_always = wfrog.css, frog_umbrella.png

[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator, weewx.reportengine.CopyGenerator
